---
# The default price in case you don't set the price of a cell
default.price: 15000
# If true, every cell will be expired after the specified days
enable.expire: true
# The days left before a cell gets deleted
expire.days: 10
# The days that will be added if players upgrade their cells
upgrade.days: 10
# The amount of money given if players sell their cells
sell.percent: 50
# The amount of money paid if players upgrade their cells
upgrade.percent: 40
# If false, it will knockback players when they try to get in to others cells
allow.movement.other.cell: false
